// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55p74EW0XzXsYEBVJijd96f4ztU3nOVY',
    appId: '1:523013675084:web:612e587a9d05f272bf3ce9',
    messagingSenderId: '523013675084',
    projectId: 'onlinedatabase-9e068',
    authDomain: 'onlinedatabase-9e068.firebaseapp.com',
    storageBucket: 'onlinedatabase-9e068.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BMuJrUIGGYlWGfdk_f7CltEVbpj_iXo',
    appId: '1:523013675084:android:745e6548fcbf7a49bf3ce9',
    messagingSenderId: '523013675084',
    projectId: 'onlinedatabase-9e068',
    storageBucket: 'onlinedatabase-9e068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBec5iwYfLQp-8OWsk8goBo32eUmxoaedc',
    appId: '1:523013675084:ios:4f2afb6eb96caed0bf3ce9',
    messagingSenderId: '523013675084',
    projectId: 'onlinedatabase-9e068',
    storageBucket: 'onlinedatabase-9e068.appspot.com',
    iosBundleId: 'com.example.onlineDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBec5iwYfLQp-8OWsk8goBo32eUmxoaedc',
    appId: '1:523013675084:ios:4f2afb6eb96caed0bf3ce9',
    messagingSenderId: '523013675084',
    projectId: 'onlinedatabase-9e068',
    storageBucket: 'onlinedatabase-9e068.appspot.com',
    iosBundleId: 'com.example.onlineDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB55p74EW0XzXsYEBVJijd96f4ztU3nOVY',
    appId: '1:523013675084:web:bff21baf50fea642bf3ce9',
    messagingSenderId: '523013675084',
    projectId: 'onlinedatabase-9e068',
    authDomain: 'onlinedatabase-9e068.firebaseapp.com',
    storageBucket: 'onlinedatabase-9e068.appspot.com',
  );
}
